config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('contact.urls'))
]

contact/urls.py
from django.urls import path
from .views import index, addContact
app_name='contact'

urlpatterns = [
    path('',index, name='index'),
    path('addContact/',addContact, name='addContact'),
]

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    fullname=models.CharField(max_length=100,null=True,blank=True)
    relationship=models.CharField(max_length=100)
    email=models.EmailField(max_length=254,null=True,blank=True)
    phone_no=models.CharField(max_length=100,null=True,blank=True)
    address=models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return self.fullname

contact/views.py
from django.shortcuts import render,redirect
from .models import Contact
# Create your views here.
def index(request):
    return render(request, 'index.html')

def addContact(request):
    if request.method=='POST':
        new_contact=Contact(
            fullname = request.POST['fullname'],
            relationship=request.POST['relationship'],
            email=request.POST['e-mail'],
           phone_no=request.POST['phone-number'],
            address=request.POST['address']
        )
        new_contact.save() 
        return render('contact:index')
    return render(request, 'new.html')

frontend/templates/contact-profile.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style-profile.css">
	
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Contact Profile</title>
</head>
<body>

	<div class="container">
		<header class="hero">
			<a href="index.html">
				<i  class="fas fa-chevron-circle-left back-btn"></i>
			</a>
			<div class="hero-info">
				<h1 class="name">Jane Doe</h1>
				<p  class="relationship">Friend</p>
			</div>
		</header>

		<section class="contact-info">

			<div class="info-line">
				<i class="fas fa-phone icon-gradient"></i>
				<p class="phone-number">888.888.888</p>
			</div>

		

			<div class="info-line">
				<i class="fas fa-sms icon-gradient"></i>
				<p class="sms">Send Message</p>
			</div>

			

			<div class="info-line">
				<i class="fas fa-envelope icon-gradient"></i>
				<p class="email">jane.doe@example.com</p>
			</div>

			

			<div class="info-line">
				<i id="location" class="fas fa-map-marker-alt icon-gradient"></i>
				<p class="address">888 Example St</p>
			</div>
		</section>

		<a href="edit.html">
			<section class="edit-contact">
				<div class="edit-button">
					<i class="fas fa-cog icon-gradient"></i>
				</div>
			</section>
		</a>
	</div>

</body>
</html>

frontend/templates/delete.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style-delete.css">
	
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Delete Contact</title>
</head>
<body>

	<div class="container">
		<header class="hero">
			<a href="edit.html">
				<i class="fas fa-chevron-circle-left back-btn"></i>
			</a>
			<div class="hero-info">
				<h1 class="name">Jane Doe</h1>
				<p class="relationship-hero">Friend</p>
			</div>
		</header>

		<section class="delete-container">
			<p>Are you sure you want to delete this contact?</p>
			<div class="delete-contact">
				<i class="fas fa-trash delete-icon"></i>
				<button class="delete-button">Delete Contact</button>
			</div>
		</section>
	</div>

</body>
</html>

frontend/templates/edit.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style-edit.css">
	
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Edit Contact</title>
</head>
<body>

	<div class="container">
		<header class="hero">
			
			<a href="contact-profile.html">
			     <i class="fas fa-chevron-circle-left back-btn"></i>
			</a>

			<div class="hero-info">
				<h1 class="name">Jane Doe</h1>
				<p class="relationship-hero">Friend</p>
			</div>
		</header>

		<section class="contact-info">

			<div class="info-line">
				<i class="fas fa-phone icon-gradient"></i>
				<input type="text" class="type" name="fullname" placeholder="Full Name">
			</div>

			<div class="info-line">
				<i class="fas fa-user-circle icon-gradient"></i>
				<input type="text" class="type" name="relationship" placeholder="Relationship">
			</div>

		

			<div class="info-line">
				<i class="fas fa-sms icon-gradient"></i>
				<input type="text" class="type" name="phone-number" placeholder="Phone Number">
			</div>

			

			<div  class="info-line">
				<i class="fas fa-envelope icon-gradient"></i>
				<input type="text" class="type" name="e-mail" placeholder="Email">
			</div>

			

			<div class="info-line">
				<i class="fas fa-map-marker-alt icon-gradient location"></i>
				<input type="text" class="type" name="address" placeholder="Address">
			</div>
			
			<div class="info-line">
				<i class="fas fa-map-marker-alt icon-gradient location"></i>
				<input type="text" class="type" name="email" placeholder="Email">
			</div>
		</section>

		<section class="button-container">
			<div class="update-contact">
				<i  class="fas fa-check-circle icon-gradient"></i>
				<button class="button">Save Contact</button>
			</div>
		</section>

		<section class="button-container">
			<a href="delete.html">
				<div class="update-contact">
					<i class="fas fa-trash icon-gradient"></i>
					<button class="button">Delete Contact</button>
				</div>
			</a>
		</section>
	</div>


</body>
</html>

frontend/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{%  static 'css/style.css' %}">
	
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	
	<title>Contact Form</title>
</head>
<body>

	<div class="container">
		<!--  SEARCH FORM -->
		<header class="header">
			
			<form class="search-bar">
				<input type="search-name" class="contact-search" name="search-area" placeholder="Search">
			</form>

			<!--  ADD-CONTACT BUTTON/ICON -->
			<!-- <a href="edit.html"><i class="fas fa-plus-circle add"></i></a> -->
			<a href="{% url 'contact:addContact' %}"><i class="fas fa-plus-circle add"></i></a>
		</header>

		<!--  CONTACT LIST -->
		<section class="contacts-library">
			<ul class="contacts-list">
				
				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">John Doe</p>
							<p class="relationship">Friend</p>
						</li>

						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Jane Doe</p>
							<p class="relationship">Friend</p>
						</li>

						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Alex Blakely</p>
							<p class="relationship">Friend</p>
						</li>

						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Sarah Smith</p>
							<p class="relationship">Family</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Johann Brooke</p>
							<p class="relationship">Family</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>


				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Sam Peterson</p>
							<p class="relationship">Family</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Sebastion Agnew</p>
							<p class="relationship">Work</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">John Doe</p>
							<p class="relationship">Friend</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>
				<div class="contact-section">
					<li class="list__item">
						<p class="contact-name">Jane Doe</p>
						<p class="relationship">Friend</p>
					</li>
					<li class="list__item">
						<i class="fas fa-phone"></i>
						<i class="fas fa-sms text"></i>
					</li>
				</div>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Alex Blakely</p>
							<p class="relationship">Friend</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Sarah Smith</p>
							<p class="relationship">Family</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Johann Brooke</p>
							<p class="relationship">Family</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Sam Peterson</p>
							<p class="relationship">Family</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>

				<a href="contact-profile.html">
					<div class="contact-section">
						<li class="list__item">
							<p class="contact-name">Sebastion Agnew</p>
							<p class="relationship">Work</p>
						</li>
						<li class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>
			</ul>
		</section>
	</div>

</body>
</html>

frontend/templates/new.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{%  static 'css/style-edit.css' %}">
	
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Edit Contact</title>
</head>
<body>

	<div class="container">
		<header class="hero">
			
			<!-- <a href="contact-profile.html"> -->
            <a href="{% url 'contact:index' %}"> 
                <i class="fas fa-chevron-circle-left back-btn"></i></a>
			  
			</a>

			<div class="hero-info">
				<h1 class="name">New Contact</h1>
				<!-- <p class="relationship-hero">Friend</p> -->
			</div>
		</header>
        <form action="" method="POST">
            {% csrf_token %} 
            <section class="contact-info">

                <div class="info-line">
                    <i class="fas fa-phone icon-gradient"></i>
                    <input type="text" class="type" name="fullname" placeholder="Full Name">
                </div>
    
                <div class="info-line">
                    <i class="fas fa-user-circle icon-gradient"></i>
                    <input type="text" class="type" name="relationship" placeholder="Relationship">
                </div>
    
            
    
                <div class="info-line">
                    <i class="fas fa-sms icon-gradient"></i>
                    <input type="text" class="type" name="phone-number" placeholder="Phone Number">
                </div>
    
                
    
                <div  class="info-line">
                    <i class="fas fa-envelope icon-gradient"></i>
                    <input type="text" class="type" name="e-mail" placeholder="Email">
                </div>
    
                
    
                <div class="info-line">
                    <i class="fas fa-map-marker-alt icon-gradient location"></i>
                    <input type="text" class="type" name="address" placeholder="Address">
                </div>
                
                <div class="info-line">
                    <i class="fas fa-map-marker-alt icon-gradient location"></i>
                    <input type="text" class="type" name="email" placeholder="Email">
                </div>
            </section>
            <section class="button-container">
                <div class="update-contact">
                    <i  class="fas fa-check-circle icon-gradient"></i>
                    <button class="button">Save Contact</button>
                </div>
            </section>
            <section class="button-container">
                <a href="delete.html">
                    <div class="update-contact">
                        <i class="fas fa-trash icon-gradient"></i>
                        <button class="button">Delete Contact</button>
                    </div>
                </a>
            </section>
    
        </form>

		
		
	</div>


</body>
</html>